Test pipeline

diff --git a/.github/workflows/lint_3.yml b/.github/workflows/lint_3.yml
--- a/.github/workflows/lint_3.yml
+++ b/.github/workflows/lint_3.yml
@@ -10,14 +10,31 @@ on:
 
 jobs:
 
-  link_checker:
+  file_checker:
     runs-on: ubuntu-latest
+
     steps:
       - name: Check out the repository
         uses: actions/checkout@v2
 
-      - name: Run LinkChecker
-        run: linkchecker http://localhost:5000
+      - name: Check if HTML files are not empty
+        run: |
+          for file in app/templates/*.html; do
+            if [ ! -s "$file" ]; then
+              echo "Error: HTML file $file is empty!" && exit 1
+            fi
+          done
+          echo "All HTML files are non-empty."
+
+      - name: Check if HTML files already exist
+        run: |
+          for file in app/templates/*.html; do
+            filename=$(basename "$file")
+            if git ls-files --error-unmatch "app/templates/$filename" > /dev/null 2>&1; then
+              echo "Error: File with the same name $filename already exists!" && exit 1
+            fi
+          done
+          echo "No duplicate HTML file names detected."
 
   html-checks:
     runs-on: ubuntu-latest
